services:
  - type: web
    name: cafe-chatbot
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn chatbot_backend:app --host 0.0.0.0 --port 5000
    envVars:
      - key: PORT
        value: 5000
